// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TableFootball;

namespace TableFootball.Migrations
{
    [DbContext(typeof(TableFootballContext))]
    [Migration("20190304083453_AddTeamsTable")]
    partial class AddTeamsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TableFootball.Models.GameEntity", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date");

                    b.Property<int>("TeamWinnerId");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TableFootball.Models.PlayerEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarUrl");

                    b.Property<int>("Games");

                    b.Property<string>("Name");

                    b.Property<int>("Points");

                    b.Property<int?>("TeamEntityTeamId");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamEntityTeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TableFootball.Models.TeamEntity", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId");

                    b.HasKey("TeamId");

                    b.HasIndex("GameId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TableFootball.Models.PlayerEntity", b =>
                {
                    b.HasOne("TableFootball.Models.TeamEntity")
                        .WithMany("Players")
                        .HasForeignKey("TeamEntityTeamId");
                });

            modelBuilder.Entity("TableFootball.Models.TeamEntity", b =>
                {
                    b.HasOne("TableFootball.Models.GameEntity", "Game")
                        .WithMany("Teams")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
